---

- hosts: localhost 
  gather_facts: false
  vars_files: 
    ./vars/main.yml

  tasks:
  - ping:

  - debug: msg="hello! ---> test project!"
  - debug: msg="{{test_var}}"

  - name: DISPLAY THE INJECTED EXTRA VAR
    debug:
      var: secret_key